### PR TITLE
Updates for the WQs in Shadowlands

### PR DESCRIPTION
**Pull request by siweia**

### CODE REVIEW

**Comment by GurliGebis** [comment]
Looks good so far - I'll take a look at the changes later. (I haven't had time to play the game since SL went live, so no characters at lvl 60 yet).

**Comment by GurliGebis** [comment]
@siweia I haven't had time to level a character yet - but if you can let me know once you have done with your changes, I'll review it and merge it.
It looks good so far, so I feel pretty confident merging them 👍

**Comment by siweia** [comment]
Its complete now.

**Comment by GurliGebis** [comment]
Thanks 👍

**Pull request merged**
